version: '3'
services:
  db:
    image: "postgres:16"
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    networks:
      - result-tier
      - back-tier
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
    networks:
      - poll-tier
  redis:
    image: "redis:7"
    restart: always
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
  worker:
    build: "./worker"
    restart: always
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    depends_on:
      db:
        condition: service_healthy
    networks:
      - back-tier
  result:
    build: "./result"
    restart: always
    ports:
      - "5001:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    depends_on:
      db:
        condition: service_healthy
    networks:
      - result-tier
volumes:
  db-data:
networks:
  poll-tier:
  result-tier:
  back-tier:

  