name : chocolatine
run-name: Running chocolatine

on: 
    pull_request:
        branches-ignore:
            - "ga-ignore-**"
    push:
        branches-ignore:
            - "ga-ignore-**"

env:
    MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga.git"
    EXECUTABLES: "a.out"

jobs:
    check_coding_style:
        if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
        runs-on: ubuntu-latest
        container: ghcr.io/epitech/coding-style-checker:latest
        steps:
            - uses: actions/checkout@v4
            - run: check.sh $(pwd) $(pwd)
            - run: |
                cat $(pwd)/coding-style-reports.log
                if [ -s $(pwd)/coding-style-reports.log ]
                then
                    IFS=$IFS:
                    while read line; do
                        infos=()
                        for i in $line; do infos+=($i) ; done
                        echo "::error file=${infos[0]},line=${infos[1]},title=${infos[2]} coding style error::${infos[3]}"
                    done < $(pwd)/coding-style-reports.log
                    exit 1
                fi
    check_program_compilation:
        if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
        runs-on: ubuntu-latest
        needs: check_coding_style
        container: epitechcontent/epitest-docker:latest
        steps:
            - uses: actions/checkout@v4
            - run: make
              timeout-minutes: 2
            - run: make clean
            - run: |
                arrEXEC=$(echo ${{ env.EXECUTABLES }} | tr "," "\n")
                for exec in $arrEXEC
                    do
                        echo ${exec}
                        if [[ ! -f $exec ]]
                            then
                                echo "::error title=$exec::Missing $exec"
                                exit 1
                        fi
                        if [[ ! -x $exec ]]
                            then
                                echo "::error title=$exec::$exec is not executable"
                                exit 1
                        fi
                    done
    run_tests:
        if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
        runs-on: ubuntu-latest
        needs: check_program_compilation
        container: epitechcontent/epitest-docker:latest
        steps:
            - uses: actions/checkout@v4
            - run: make tests_run
              timeout-minutes: 2
    push_to_mirror:
        if: github.repository != env.MIRROR_URL  && github.event_name  == 'push'
        runs-on: ubuntu-latest
        needs: run_tests
        steps:
            - run: echo ${{ github.event_name }} ${{ github.repository }}
            - uses: actions/checkout@v4
              with:  
                fetch-depth: 0 
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                    ${{ env.MIRROR_URL }}
                ssh_private_key:
                    ${{ secrets.GIT_SSH_PRIVATE_KEY }}