name : chocolatine
run-name: Running chocolatine

on: 
    pull_request:
        branches-ignore:
            - "ga-ignore-**"
    push:
        branches-ignore:
            - "ga-ignore-**"

env:
    MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga.git"
    EXECUTABLES: "mysh"

jobs:
    mirror:
        if: github.repository != '$MIRROR_URL'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                    ${{ env.MIRROR_URL }}
                ssh_private_key:
                    ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    check_coding_style:
        if: github.repository != '$MIRROR_URL'
        container: ghcr.io/epitech/coding-style-checker:latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                check.sh $(pwd) $(pwd)
                cat $(pwd)/coding-style-reports.log
                if [[ -s $(pwd)/coding-style-reports.log ]]
                then
                    exit 1
                fi
                        