name : chocolatine
run-name: Running chocolatine

on: 
    pull_request:
        branches-ignore:
            - "ga-ignore-**"
    push:
        branches-ignore:
            - "ga-ignore-**"

env:
    MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga.git"
    EXECUTABLES: "mysh"

jobs:
    check_coding_style:
        if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
        container: ghcr.io/epitech/coding-style-checker:latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                check.sh $(pwd) $(pwd)
                cat $(pwd)/coding-style-reports.log
                if [[ -s $(pwd)/coding-style-reports.log ]]
                then
                    exit 1
                fi
    check_program_compilation:
        if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
        runs-on: ubuntu-latest
        needs: check_coding_style
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo ${{ github.repository }}
    # mirror:
    #     if: github.repository != 'EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga'
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: pixta-dev/repository-mirroring-action@v1
    #             with:
    #             target_repo_url:
    #                 ${{ env.MIRROR_URL }}
    #             ssh_private_key:
    #                 ${{ secrets.GIT_SSH_PRIVATE_KEY }}